name: Python/Envs

on:
  push:
    branches:
      - main
      - arthur/conda-env-use-uv
    # paths:
    #   - 'test-species/**'

jobs:
  upload_env:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-22.04]
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Run step when directory changes
        run: echo "This workflow runs only when files in 'my-directory' are modified."

      - name: Install Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: species-env
          python-version: '3.11'
          auto-update-conda: true

      - name: Install Python dependencies
        shell: bash -l {0}
        run: |
          conda run pip install -r ./test-species/pyproject.toml
          conda list

      - name: Compress conda environment
        shell: bash -l {0}
        run: |
          mkdir -p dist
          CONDA_BASE=$(conda info --base)
          CONDA_ENV_PATH=$CONDA_BASE/envs/species-env

          tar -czf dist/species-env-${{ runner.os }}-with-uv.tar.gz -C $CONDA_BASE/envs species-env

      - name: Upload to Cloudflare R2
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }}
          endpoint: ${{ secrets.CLOUDFLARE_R2_ENDPOINT }}
          source_dir: dist
          destination_dir: conda-environments
