name: Python/Poetry/Envs

on:
  push:
    branches:
      - main
    paths:
      - 'poet/**'

jobs:
  upload_env:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        env:
          POETRY_VIRTUALENVS_OPTIONS_NO_PIP: 1
          POETRY_VIRTUALENVS_CREATE: 1
          POETRY_VIRTUALENVS_IN_PROJECT: 1
          POETRY.VIRTUALENVS_ALWAYS_COPY: 1

      - name: Install dependencies
        run: |
          cd poet
          poetry install --no-root

      - name: Compress env
        run: |
          cd poet
          tar -czf dist/poet.tar.gz .venv

      - name: Upload to Cloudflare R2
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }}
          endpoint: ${{ secrets.CLOUDFLARE_R2_ENDPOINT }}
          source_dir: dist
          destination_dir: poetry-environments
